package com.ger.garage.model;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;

/*

Class shifts: represent a shift in the system. Mechanic can be assigned to shifts.
Every shift has 4 slots. It is represented in the database

 */

public class Shift {

    private Integer id;
    private String description;
    private LocalTime timeStart;
    private LocalTime timeEnd;

    public Shift(Integer id) {
        this.id = id;
    }

    public Shift(Integer id, String description, LocalTime timeStart, LocalTime timeEnd) {
        this.id = id;
        this.description = description;
        this.timeStart = timeStart;
        this.timeEnd = timeEnd;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public LocalTime getTimeStart() {
        return timeStart;
    }

    public void setTimeStart(LocalTime timeStart) {
        this.timeStart = timeStart;
    }

    public LocalTime getTimeEnd() {
        return timeEnd;
    }

    public void setTimeEnd(LocalTime timeEnd) {
        this.timeEnd = timeEnd;
    }

    @Override
    public String toString() {
        String pattern = "hh:mm:ss a";
        return this.id + " - "+ timeStart.format((DateTimeFormatter.ofPattern(pattern)));
    }

    // Create a shift using the string input which is generated by toString()
    // NO MODIFY THIS METHOD - DEPENDS ON TOSTRING() METHOD
    public static Shift valueOf(String shift) {

        String[] shiftInfo =  shift.split(" ");
        return new Shift(Integer.parseInt(shiftInfo[0]));
    }

}
