package com.ger.garage.model;

/*

    Class vehicle: numberplate contains data about a vehicle.

*/

public class Vehicle {

    private String numberPlate;
    private Make make;
    private String engineType;
    private String type;

    public Vehicle(Make make, String numberPlate, String engineType, String type) {
        this.make = make;
        this.numberPlate = numberPlate;
        this.engineType = engineType;
        this.type = type;
    }

    public Make getMake() {
        return make;
    }

    public void setMake(Make make) {
        this.make = make;
    }


    public Vehicle(String numberPlate) {
        this.numberPlate = numberPlate;
    }

    public Vehicle() {
    }

    public String getNumberPlate() {
        return numberPlate;
    }

    public void setNumberPlate(String numberPlate) {
        this.numberPlate = numberPlate;
    }

    public String getEngineType() {
        return engineType;
    }

    public void setEngineType(String engineType) {
        this.engineType = engineType;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    @Override
    public String toString() {
        return  make + " - " +  numberPlate;
    }

    // Value of Make - numberPlate string
    // Create a vehicle using the string input which is generated by toString()
    // NO MODIFY THIS METHOD - DEPENDS ON TOSTRING() METHOD
    public static Vehicle valueOf(String vehicle) {

        String[] vehicleInfo =  vehicle.split(" ");
        return new Vehicle(vehicleInfo[2]);

    }

}
